services:
    dimetrodon.loginsearch.listener:
        class: dimetrodon\loginsearch\event\main_listener
        arguments:
            - '@language'
            - '@auth'
        tags:
            - { name: event.listener }
